#Parte Andrei

#importar e ler ficheiro
library(readxl)
hour <- read_excel("C:/Users/andre/Desktop/ME/TP1/hour.xlsx")
View(hour)

### Todos os alugueres entre as 7 às 18
hour.day <- subset(hour, 6<hr & hr<19)
View(hour.day)

### ver o tipo de dados
str(hour.day)

# ver as primeira linhas
head(hour.day)
# ver as últimas linhas
tail(hour.day)

### tabela frequencias
local({
  .Table <- with(hour, table(hr))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})

##################################################
#quartis
summary(hour.day)

## **1. temp** {#temp}

### Classificação da variável

Variável Quantitativa Discreta, e é tratada como quantitativa discreta normal,
visto que, não tem grande variedade de variaveis distintas.

table(hour.day$temp)

### Moda da temperatura
hour.day.temp.sort <- sort(hour.day$temp)
hour.day.temp.mode <- moda(hour.day.temp.sort)
hour.day.temp.mode
# 0.7


### Média da temperatura
hour.day.temperatura.media <- mean(hour.day$temp)
hour.day.temperatura.media
# 0.5237

### Mediana 
hour.day.temperatura.mediana <- median(hour.day$temp)
hour.day.temperatura.mediana
# 0.52

### Quartil
hour.day.temperatura.quantile <- quantile(hour.day$temp)
hour.day.temperatura.quantile
# 0%  25%  50%  75% 100% 
#0.02 0.36 0.52 0.70 1.00

### Medidas de Dispersão Central

### Variância
hour.day.temperatura.variancia <- var(hour.day$temp)
hour.day.temperatura.variancia
# 0.0401759

### Desvio Padrão
hour.day.temperatura.desvio_padrao <- sd(hour.day$temp)
hour.day.temperatura.desvio_padrao
# 0.2004393

### Coeficiente de Variação
hour.day.temperatura.coeficiente_variacao <- coeficiente_variacao(hour.day$temp)
hour.day.temperatura.coeficiente_variacao
# 38.27561

### Valores Extremos

### Máximo
hour.day.temperatura.maxima <- max(hour.day$temp)
hour.day.temperatura.maxima
# 1

### Mínimo
hour.day.temperatura.minima <- min(hour.day$temp)
hour.day.temperatura.minima
# 0.02

### Medidas de Assimetria
hour.day.temperatura.assimetria <- assimetria(hour.day$temp)
hour.day.temperatura.assimetria
#-0.03380892
# Logo conclui-se que é assimétrica negativa fraca (ou enviesada para a esquerda)

### Medidas de Curtose ou Achatamento
hour.day.temperatura.achatamento <- achatamento(hour.day$temp)
hour.day.temperatura.achatamento
#-0.998132
# Logo conclui.se Curva platicúrtica, achatada, o que significa
# que os valores estão muito concentrados em torno da média e, consequentemente,
# existe uma variação baixa.

### Histograma

# formula de sturges
cat("Número de classes\n")
hour.day.temp.sturges.nclass <- sturges(hour.day$temp)
hour.day.temp.sturges.nclass
# 14 classes


# amplitude da classe
cat("\nAmplitude da classe\n")
hour.day.temp.sturges.amplitude <- amplitude(hour.day$temp)
hour.day.temp.sturges.amplitude
# amplitude por classe 0.07

# tabela de frequencias
cat("\nClasses\n")
hour.day.temp.sturges.breaks <- seq(hour.day.temperatura.minima, hour.day.temperatura.maxima, hour.day.temp.sturges.amplitude)
hour.day.temp.sturges.breaks
# 0.02 0.09 0.16 0.23 0.30 0.37 0.44 0.51 0.58 0.65 0.72 0.79 0.86 0.93 1.00

cat("\nTabela de frequências\n")
table(cut(hour.day$temp, breaks=hour.day.temp.sturges.breaks))

# histograma
hist(hour.day$temp, main="Histograma Temperature during the day", xlab="Temperature",  ylab="Indice", nclass=hour.day.temp.sturges.nclass)
# A partir do histograma, pode-se observar que o valor do índice aumenta no intervalo 0.02, a 1,  tendo um comportamento crescente 
# até atingir o maior índice no intervalo de  0.65 a 0.72.

### Diagrama de Extremos e Quartis 

# Outliers
cat("\nOutliers\n")
hour.day.temperatura.outliers <- boxplot.stats(hour.day$temp)$out
hour.day.temperatura.outliers

# Diagrama
boxplot(hour.day$temp, ylab="Temperatura", main="Boxplot Temperatura")
mtext(text = paste("outliers: ", paste(hour.day.temperatura.outliers, collapse = ", ")), side = 1)

# Verificou-se que não existem outliers presentes no gráfico.

########################################################
########################################################

## **2. weekday** {#weekday}

### Classificação da variável

Variável qualitativa ordinal, e é tratada como quantitativa discreta normal,
visto que, não tem grande variedade de variaveis distintas.

table(hour.day$weekday)

### Moda do dia da semana
hour.day.weekday.sort <- sort(hour.day$weekday)
hour.day.weekday.mode <- moda(hour.day.weekday.sort)
hour.day.weekday.mode
# 0 - domingo


### Média do dia da semana
hour.day.weekday.media <- mean(hour.day$weekday)
hour.day.weekday.media
# 2.999886

### Mediana 
hour.day.weekday.mediana <- median(hour.day$weekday)
hour.day.weekday.mediana
# 3

### Quartil
hour.day.weekday.quantile <- quantile(hour.day$weekday)
hour.day.weekday.quantile
# 0%  25%  50%  75% 100% 
#0    1    3    5    6

### Medidas de Dispersão Central

### Variância
hour.day.weekday.variancia <- var(hour.day$weekday)
hour.day.weekday.variancia
# 4.020945

### Desvio Padrão
hour.day.weekday.desvio_padrao <- sd(hour.day$weekday)
hour.day.weekday.desvio_padrao
# 2.00523

### Coeficiente de Variação
hour.day.weekday.coeficiente_variacao <- coeficiente_variacao(hour.day$weekday)
hour.day.weekday.coeficiente_variacao
# 66.84353

### Valores Extremos

### Máximo
hour.day.weekday.maxima <- max(hour.day$weekday)
hour.day.weekday.maxima
# 6

### Mínimo
hour.day.weekday.minima <- min(hour.day$weekday)
hour.day.weekday.minima
# 0

### Medidas de Assimetria
hour.day.weekday.assimetria <- assimetria(hour.day$weekday)
hour.day.weekday.assimetria
#-0.0001836458
# Logo conclui-se que é assimétrica negativa fraca (ou enviesada para a esquerda)

### Medidas de Curtose ou Achatamento
hour.day.weekday.achatamento <- achatamento(hour.day$weekday)
hour.day.weekday.achatamento
#-1.255535
# Logo conclui.se Curva platicúrtica, achatada, o que significa
# que os valores estão muito concentrados em torno da média e, consequentemente,
# existe uma variação baixa.

### Histograma

# formula de sturges
cat("Número de classes\n")
hour.day.weekday.sturges.nclass <- sturges(hour.day$weekday)
hour.day.weekday.sturges.nclass
# 14 classes


# amplitude da classe
cat("\nAmplitude da classe\n")
hour.day.weekday.sturges.amplitude <- amplitude(hour.day$weekday)
hour.day.weekday.sturges.amplitude
# amplitude por classe 0.4285714

# tabela de frequencias
cat("\nClasses\n")
hour.day.weekday.sturges.breaks <- seq(hour.day.weekday.minima, hour.day.weekday.maxima, hour.day.weekday.sturges.amplitude)
hour.day.weekday.sturges.breaks
# 0.0000000 0.4285714 0.8571429 1.2857143 1.7142857 2.1428571 2.5714286 3.0000000 3.4285714 3.8571429
# 4.2857143 4.7142857 5.1428571 5.5714286 6.0000000

cat("\nTabela de frequências\n")
table(cut(hour.day$weekday, breaks=hour.day.weekday.sturges.breaks))

# histograma
hist(hour.day$weekday, main="Histograma Weekday", xlab="Weekday",  ylab="Indice", nclass=hour.day.weekday.sturges.nclass)
# A partir do histograma, pode-se observar que o valor do índice mantém se no intervalo 0 a 6,  tendo um comportamento
# crescente até atingir o maior índice no intervalo de  5.6 a 6.

### Diagrama de Extremos e Quartis 

# Outliers
cat("\nOutliers\n")
hour.day.weekday.outliers <- boxplot.stats(hour.day$weekday)$out
hour.day.weekday.outliers

# Diagrama
boxplot(hour.day$weekday, ylab="Temperatura", main="Boxplot Temperatura")
mtext(text = paste("outliers: ", paste(hour.day.weekday.outliers, collapse = ", ")), side = 1)

# Verificou-se que não existem outliers presentes no gráfico.
